### ISSUE TITLE
bazel build failing in cloud build

### ISSUE THREAD

**Issue by srellik** [GoogleCloudPlatform/cloud-builders#319]
I am using grpc-java and dagger2 in my service. I am using java_image rule to build docker image. The target is successfully building in both MacOS and Ubuntu, but always failing in Google Cloud build using gcr.io/cloud-builders/bazel.

I am not able to find the issue, could someone help in tracking down this issue. Thanks in advance.

ERROR: /workspace/......./src/main/java/com/srellik/......./service/usermgmt/BUILD:6:1: Building ......./src/main/java/com/srellik/......./service/usermgmt/libservice.jar (4 source files) and running annotation processors (GrpcServiceProcessor, ComponentProcessor) failed (Exit 1): java failed: error executing command 
(cd /builder/home/.cache/bazel/_bazel_root/eab0d61a99b6696edb3d2aff87b585e8/execroot/__main__ && \
exec env - \
LC_CTYPE=en_US.UTF-8 \
external/embedded_jdk/bin/java -XX:+UseParallelOldGC -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.comp=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED' '--add-opens=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED' '--patch-module=java.compiler=external/bazel_tools/third_party/java/jdk/langtools/java_compiler.jar' '--patch-module=jdk.compiler=external/bazel_tools/third_party/java/jdk/langtools/jdk_compiler.jar' '--add-opens=java.base/java.nio=ALL-UNNAMED' -jar external/bazel_tools/tools/jdk/JavaBuilder_deploy.jar @bazel-out/k8-fastbuild/bin/......./src/main/java/com/srellik/......./service/usermgmt/libservice.jar-2.params)
......./src/main/java/com/srellik/......./service/usermgmt/UserMgmtSubComponent.java:19: error: cannot find symbol
public interface UserMgmtSubComponent extends UserMgmtServiceDefinition {
^
symbol: class UserMgmtServiceDefinition
......./src/main/java/com/srellik/......./service/usermgmt/UserMgmtModule.java:10: error: cannot find symbol
abstract UserMgmtServiceDefinition userMgmtSubComponent(
^
symbol: class UserMgmtServiceDefinition
location: class UserMgmtModule
......./src/main/java/com/srellik/......./service/usermgmt/UserMgmtSubComponent.java:13: error: cannot find symbol
UserMgmtGrpcServiceModule.class,
^
symbol: class UserMgmtGrpcServiceModule
java.lang.RuntimeException: java.lang.NoClassDefFoundError: javax/annotation/Generated
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
at com.google.devtools.build.buildjar.javac.BlazeJavacMain.compile(BlazeJavacMain.java:110)
at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder$2.invokeJavac(SimpleJavaLibraryBuilder.java:122)
at com.google.devtools.build.buildjar.ReducedClasspathJavaLibraryBuilder.compileSources(ReducedClasspathJavaLibraryBuilder.java:65)
at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.compileJavaLibrary(SimpleJavaLibraryBuilder.java:125)
at com.google.devtools.build.buildjar.SimpleJavaLibraryBuilder.run(SimpleJavaLibraryBuilder.java:133)
at com.google.devtools.build.buildjar.BazelJavaBuilder.processRequest(BazelJavaBuilder.java:105)
at com.google.devtools.build.buildjar.BazelJavaBuilder.runPersistentWorker(BazelJavaBuilder.java:67)
at com.google.devtools.build.buildjar.BazelJavaBuilder.main(BazelJavaBuilder.java:45)
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Generated
at dagger.grpc.server.processor.GrpcServiceModel.generatedAnnotation(GrpcServiceModel.java:115)
at dagger.grpc.server.processor.ServiceDefinitionTypeGenerator.createType(ServiceDefinitionTypeGenerator.java:46)
at dagger.grpc.server.processor.SourceGenerator.javaFile(SourceGenerator.java:36)
at dagger.grpc.server.processor.GrpcServiceProcessor.write(GrpcServiceProcessor.java:79)
at dagger.grpc.server.processor.GrpcServiceProcessor.process(GrpcServiceProcessor.java:69)
at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:329)
at dagger.shaded.auto.common.BasicAnnotationProcessor.process(BasicAnnotationProcessor.java:182)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:884)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$2200(JavacProcessingEnvironment.java:108)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1206)
at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1315)
at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)
at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
... 10 more
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
at java.base/java.net.URLClassLoader.findClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
... 26 more
Target //......./src/main/java/com/srellik/.......:grpc_server_image failed to build
INFO: Elapsed time: 449.934s, Critical Path: 28.97s
INFO: 283 processes: 260 local, 23 worker.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully

**Comment by bendory** [comment]
I checked with our Google internal bazel team who gave me the following answer:

> the error you are seeing is because Bazel upgraded its embedded JDK to JDK9 and there the
javax.annotation.Generated has been removed from the JDK. Multiple users hit this issue and
the solution is to either use your own JDK8 that still ships this class or upgrade Dagger to a
more recent version that works with Java 9.
