### ISSUE TITLE
gcloud crash on cloud-builders/gcloud but works fine on local

### ISSUE THREAD

**Issue by apolkingg8** [GoogleCloudPlatform/cloud-builders#470]
## Affected builder image

`gcr.io/cloud-builders/gcloud`

## Expected Behavior

Deploy to app engine.

## Actual Behavior

gcloud crashed
```log
Already have image (with digest): gcr.io/cloud-builders/gcloud
DEBUG: Running [gcloud.app.deploy] with arguments: [--quiet: "True", --verbosity: "debug", DEPLOYABLES:1: "[u'web-studio.app.yaml']"]
DEBUG: API endpoint: [https://appengine.googleapis.com/], API version: [v1]
Services to deploy:

descriptor: [/workspace/web-studio.app.yaml]
source: [/workspace]
target project: [project-name]
target service: [default]
target version: [20190311t044440]
target url: [https://project-name.appspot.com]


DEBUG: No bucket specified, retrieving default bucket.
DEBUG: Using bucket [gs://staging.project-name.appspot.com].
Beginning deployment of service [default]...
INFO: Using .gcloudignore file at [/workspace/.gcloudignore].
DEBUG: Skipping file [.gcloudignore]
DEBUG: Skipping file [.gitignore]
DEBUG: Skipping file [.git]
DEBUG: Skipping file [node_modules]
DEBUG: 'ascii' codec can't decode byte 0xef in position 60: ordinal not in range(128)
Traceback (most recent call last):
File "/builder/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 987, in Execute
resources = calliope_command.Run(cli=self, args=args)
File "/builder/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 795, in Run
resources = command_instance.Run(args)
File "/builder/google-cloud-sdk/lib/surface/app/deploy.py", line 90, in Run
parallel_build=False)
File "/builder/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 624, in RunDeploy
flex_image_build_option=flex_image_build_option)
File "/builder/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/deploy_util.py", line 400, in Deploy
service_info.env, service.source)
File "/builder/google-cloud-sdk/lib/googlecloudsdk/command_lib/app/source_files_util.py", line 159, in GetSourceFiles
return list(it)
File "/builder/google-cloud-sdk/lib/googlecloudsdk/command_lib/util/gcloudignore.py", line 232, in GetIncludedFiles
upload_directory, followlinks=True):
File "/usr/lib/python2.7/os.py", line 296, in walk
for x in walk(new_path, topdown, onerror, followlinks):
File "/usr/lib/python2.7/os.py", line 296, in walk
for x in walk(new_path, topdown, onerror, followlinks):
File "/usr/lib/python2.7/os.py", line 296, in walk
for x in walk(new_path, topdown, onerror, followlinks):
File "/usr/lib/python2.7/os.py", line 296, in walk
for x in walk(new_path, topdown, onerror, followlinks):
File "/usr/lib/python2.7/os.py", line 296, in walk
for x in walk(new_path, topdown, onerror, followlinks):
File "/usr/lib/python2.7/os.py", line 286, in walk
if isdir(join(top, name)):
File "/usr/lib/python2.7/posixpath.py", line 73, in join
path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 60: ordinal not in range(128)
ERROR: gcloud crashed (UnicodeDecodeError): 'ascii' codec can't decode byte 0xef in position 60: ordinal not in range(128)

If you would like to report this issue, please run the following command:
gcloud feedback

To check gcloud for common problems, please run the following command:
gcloud info --run-diagnostics
```

## Steps to Reproduce the Problem

deploy yaml
```yaml
steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['web-studio:build']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'web-studio.app.yaml', '--quiet', '--verbosity', 'debug']
```

web-studio.app.yaml
```yaml
runtime: nodejs10

instance_class: F1

service: default

env_variables:
  PACKAGE_NAME: "web-studio"

handlers:
  - url: /.*
    script: auto
```

## Additional Info

Deploy same project on local works fine.

**Comment by apolkingg8** [comment]
I solved it. Configures are fine, but one of my test file has non-supported charter. Everything works fine after ignore them.
