### ISSUE TITLE
functions deploy with private npm modules fails without any useful error

### ISSUE THREAD

**Issue by leftieFriele** [GoogleCloudPlatform/cloud-builders#621]
## Affected builder image

`gcr.io/cloud-builders/functions`

## Expected Behavior
Function deployed successfully.
## Actual Behavior
Build fails without any useful error message or log trace.

## Additional Info

I followed the advice in #354, however I need to deploy a Cloud Function.
Here is my build config
```
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - kms
  - decrypt
  - --ciphertext-file=npmrc.enc
  - --plaintext-file=/root/.npmrc
  - --location=global
  - --keyring=my-keys
  - --key=npm-key
  volumes:
  - name: 'home'
    path: /root/
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
  dir: 'functions/autodeploy'
  env:
  - HOME=/root/
  volumes:
  - name: 'home'
    path: /root/
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'functions',
    'deploy',
    'myFunction',
    '--trigger-http',
    '--runtime', 'nodejs10',
    '--entry-point', 'handleRequest'
    ]
  env:
  - HOME=/root/
  volumes:
  - name: 'home'
    path: /root/
```

This leads to an error in Cloud Build:
```
failed.
Step #2: DEBUG: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: Build error details not available
Step #2: Traceback (most recent call last):
Step #2:   File "/builder/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 981, in Execute
Step #2:     resources = calliope_command.Run(cli=self, args=args)
Step #2:   File "/builder/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
Step #2:     resources = command_instance.Run(args)
Step #2:   File "/builder/google-cloud-sdk/lib/surface/functions/deploy.py", line 309, in Run
Step #2:     return _Run(args, track=self.ReleaseTrack())
Step #2:   File "/builder/google-cloud-sdk/lib/surface/functions/deploy.py", line 265, in _Run
Step #2:     op, do_every_poll=TryToSetInvokerPermission)
Step #2:   File "/builder/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/util.py", line 306, in CatchHTTPErrorRaiseHTTPExceptionFn
Step #2:     return func(*args, **kwargs)
Step #2:   File "/builder/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/util.py", line 353, in WaitForFunctionUpdateOperation
Step #2:     do_every_poll=do_every_poll)
Step #2:   File "/builder/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/operations.py", line 137, in Wait
Step #2:     _WaitForOperation(client, request, notice, do_every_poll)
Step #2:   File "/builder/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/operations.py", line 111, in _WaitForOperation
Step #2:     sleep_ms=SLEEP_MS)
Step #2:   File "/builder/google-cloud-sdk/lib/googlecloudsdk/core/util/retry.py", line 219, in RetryOnResult
Step #2:     result = func(*args, **kwargs)
Step #2:   File "/builder/google-cloud-sdk/lib/googlecloudsdk/api_lib/functions/operations.py", line 70, in _GetOperationStatus
Step #2:     raise exceptions.FunctionsError(OperationErrorToString(op.error))
Step #2: FunctionsError: OperationError: code=3, message=Build failed: Build error details not available
Step #2: ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: Build error details not available
Finished Step #2
ERROR
ERROR: build step 2 "gcr.io/cloud-builders/gcloud" failed: step exited with non-zero status: 1
``` 

With --log-http enabled this is the requests where it fails:
```
== body end ==
Step #2: ==== request end ====
Step #2: ---- response start ----
Step #2: -- headers start --
Step #2: -content-encoding: gzip
Step #2: cache-control: private
Step #2: content-length: 1684
Step #2: content-location: https://cloudfunctions.googleapis.com/v1/operations/dmliYmlvZXhwcmVzcy9ldXJvcGUtd2VzdDEvc2VuZGVtYWlsLXN0YWdpbmcvUGU2WHVNOEl0RGc?alt=json
Step #2: content-type: application/json; charset=UTF-8
Step #2: date: Mon, 10 Feb 2020 10:07:15 GMT
Step #2: server: ESF
Step #2: status: 200
Step #2: transfer-encoding: chunked
Step #2: vary: Origin, X-Origin, Referer
Step #2: x-content-type-options: nosniff
Step #2: x-frame-options: SAMEORIGIN
Step #2: x-xss-protection: 0
Step #2: -- headers end --
Step #2: -- body start --
Step #2: {
Step #2:   "name": "operations/dmliYmlvZXhwcmVzcy9ldXJvcGUtd2VzdDEvc2VuZGVtYWlsLXN0YWdpbmcvUGU2WHVNOEl0RGc",
Step #2:   "metadata": {
Step #2:     "@type": "type.googleapis.com/google.cloud.functions.v1.OperationMetadataV1",
Step #2:     "target": "projects/vibbioexpress/locations/europe-west1/functions/sendemail-staging",
Step #2:     "type": "CREATE_FUNCTION",
Step #2:     "request": {
Step #2:       "@type": "type.googleapis.com/google.cloud.functions.v1.CloudFunction",
Step #2:       "name": "projects/myprojects/locations/europe-west1/functions/myFunction",
Step #2:       "httpsTrigger": {},
Step #2:       "entryPoint": "handleRequest",
Step #2:       "labels": {
Step #2:         "deployment-tool": "cli-gcloud"
Step #2:       },
Step #2:       "sourceUploadUrl": "..........",
Step #2:       "environmentVariables": {
Step #2:       },
Step #2:       "runtime": "nodejs10"
Step #2:     },
Step #2:     "versionId": "1",
Step #2:     "updateTime": "2020-02-10T10:07:14Z"
Step #2:   },
Step #2:   "done": true,
Step #2:   "error": {
Step #2:     "code": 3,
Step #2:     "message": "Build failed: Build error details not available"
Step #2:   }
Step #2: }
Step #2: 
Step #2: -- body end --
Step #2: total round trip time (request+response): 0.381 secs
Step #2: ---- response end ----
Step #2: ----------------------
```
No errors are logged anywhere and the function isn't deployed.

**Comment by bendory** [comment]
For assistance with the hosted GCB service or other GCP products and services, please contact your Google support representative.
